### ISSUE TITLE
增加语音聊天功能？

### ISSUE THREAD

**Issue by ejacky** [good-life/PushTalk#20]
可否增加语音功能？

**Comment by xiezefan** [comment]
Hi, PushTalk已经不再维护， 推荐您使用我们的新即时通讯SDK [JMessage](https://www.jpush.cn/common/im) 
JMessage 与 PushTalk 一样是基于JPush的**即时通讯解决方案**
JMessage 支持发送语音与图片 :)

**Comment by ejacky** [comment]
有github 链接吗？

**Comment by xiezefan** [comment]
Hi, See it  
 [JMessage Demo](https://www.jpush.cn/common/downloads/sdk/im_android/)  
 [JMessage 开发文档](http://docs.jpush.io/guideline/jmessage_guide/)

**Comment by ejacky** [comment]
thanks

**Comment by ejacky** [comment]
有论坛可以讨论吗？ 

我执行 JMessage 的sdk ， 报 
Error:Android Dex: [JMessageDemo] com.android.dex.DexException: Multiple dex files define Lcn/jpush/android/util/c;

问题。

**Comment by xiezefan** [comment]
你可以通过QQ群：373349994 获得免费的技术支持。:)

**Comment by ejacky** [comment]
QQ 群 没有加我 ， 能给个 JMessage 的测试appkey 吗？

**Comment by xiezefan** [comment]
Hi, 你可以直接在[JPush控制台](https://www.jpush.cn/common/apps)创建测试APP。
技术支持QQ群你再加一次试一试。
